export const inputFormElement=[
    {
        name:"firstname",
        placeholder:"Enter First Name",
        label:"First Name",
        variant:"outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm:6,
        size:"small",
    },
    {
        name:"lastname",
        placeholder:"Enter Last Name",
        label:"Last Name",
        variant:"outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm:6,
        size:"small",
    },
    {
        name:"email",
        type:"email",
        placeholder:"Enter Email",
        label:"Email",
        variant:"outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm:6,
        size:"small",
    },
    {
        name:"phone",
        type:"number",
        placeholder:"Enter Phone Number",
        label:"Phone Number",
        variant:"outlined",
        fullWidth: true,
        required: false,
        xs: 12,
        sm:6,
        size:"small",
    },
    {
        name:"message",
        placeholder:"Enter your message here",
        label:"Your Message",
        variant:"outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 12,
        size: "small",
    }
]